import { Quote } from './quote';

export const QUOTES: Quote[] = [
  { id: 1, name: 'Life is beautiful' },
  { id: 2, name: 'Embrace the storm' },
  { id: 3, name: 'Find beauty in the clouds' },
  { id: 4, name: 'Be the change you wish to see' },
  { id: 5, name: 'Dream big and work hard' },
  { id: 6, name: 'Embrace the fog of uncertainty' },
  { id: 7, name: 'Gratitude is the best attitude' },
  { id: 8, name: 'Let the wind carry you forward' },
  { id: 9, name: 'Live in the moment' },
  { id: 10, name: 'Chase your dreams' },
  { id: 11, name: 'Learn from your mistakes' },
  { id: 12, name: 'Stay positive and keep smiling' },
  { id: 13, name: 'Seize the day' },
  { id: 14, name: 'Believe in yourself' },
  { id: 15, name: 'Find joy in the little things' },
  { id: 16, name: 'Spread love and kindness' },
  { id: 17, name: 'Embrace change' },
  { id: 18, name: 'Stay curious and never stop learning' },
  { id: 19, name: 'Keep your head up and your heart strong' },
  { id: 20, name: 'Live with purpose' },
  { id: 21, name: 'Be fearless in the pursuit of your goals' },
  { id: 22, name: 'Choose happiness every day' },
  { id: 23, name: 'Celebrate your successes, big and small' },
  { id: 24, name: 'Find solace in nature' },
  { id: 25, name: 'Remember that every moment is a gift' },
];
